config/routes.rb
Rails.application.routes.draw do
  root 'movies#search'
  get 'movies/search'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def search
    @title = params['title']

    # sets my initial query string
    query_url = 'http://api.rottentomatoes.com/api/public/v1.0/movies.json'
    api_key = '2pwuxewequbju5pc2ksqfphx'
    # adds movie title to end of QUERY constent and stores raw json
    uri = URI("#{query_url}?apikey=#{api_key}&q=#{@title}")
    raw_json = Net::HTTP.get(uri)

    # returns movies array containing hash key values of supporting information
    results = JSON.parse(raw_json)['movies']
    # sets first hash result to movie

    unless results.blank?
      @movie = results.first
      # set variables
      @movie_title = @movie['title']
          @movie_title = 'No Movie Returned' if @movie_title.blank?
      @movie_synopsis = @movie['synopsis']
        @movie_synopsis = 'There are no words to describe this movie.' if @movie_synopsis.blank?
      @movie_year = @movie['year']
        @movie_year = 'No year listed.' if @movie_year.blank?
      @movie_mpaa_rating = @movie['mpaa_rating']
        @movie_mpaa_rating = 'NR' if @movie_mpaa_rating.blank?
      @movie_runtime = @movie['runtime']
        @movie_runtime = 'Not listed.' if @movie_runtime.blank?

      @movie_rating_audience = @movie['ratings']['audience_rating']
        @movie_rating_audience = 'Not Reviewed' if @movie_rating_audience.blank?
      @movie_rating_a_score = @movie['ratings']['audience_score']
        @movie_rating_a_score = 'No Review Score' if @movie_rating_a_score.blank?
      @movie_rating_critics =  @movie['ratings']['critics_rating']
        @movie_rating_critics = 'Not Reviewed' if @movie_rating_critics.blank?
      @movie_rating_c_score = @movie['ratings']['critics_score']
        @movie_rating_c_score = 'No Review Score' if @movie_rating_c_score.blank?

      @movie_release_theater = @movie['release_dates']['theater']
        @movie_release_theater = Date.parse(@movie_release_theater) unless @movie_release_theater.blank?
      @movie_release_dvd = @movie['release_dates']['dvd']
        @movie_release_dvd = Date.parse(@movie_release_dvd) unless @movie_release_dvd.blank?

      @movie_poster_thumb = @movie['posters']['thumbnail']
      # image sizes = det / ori / pro / tmb
      @movie_poster_original = @movie_poster_thumb.gsub(/tmb.jpg/, 'ori.jpg')
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieQuery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Arvo:400,400italic' rel='stylesheet' type='text/css'>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>

<body class="font">

  <div class="container">
      <%= yield %>
  </div>
  <footer class="pull-right"><i><small>A Swizzle Sticks Creation</small></i></footer>
</body>

</html>

app/views/movies/search.html.erb
<% if @title.blank? %>
  <div class="jumbotron">
    <h1>Search For a Flick</h1>
  </div>

  <%= form_tag(root_path, method: "get", class:"form-inline", style:"padding-left:300px;") do %>
    <div class="form-group">
      <%= label_tag(:title, "Movie Title:") %>
      <%= text_field_tag(:title, nil, class: "form-control", placeholder: "Enter Movie Title") %>
    </div>
    <button type="submit" class="btn btn-default">Search</button>
  <% end %>

<% else %>

  <%= form_tag(movies_search_path, method: "get", class:"form-inline", style:"padding:10px;") do %>
  <div class="form-group">
    <%= label_tag(:title, "Movie Title:") %>
    <%= text_field_tag(:title, nil, class: "form-control", placeholder: "Enter Movie Title") %>
  </div>
  <button type="submit" class="btn btn-default">Search</button>
  <% end %>


  <% if @movie.blank? %>
    <div class="jumbotron">
      <h1><%= @title %> could not be found</h1>
    </div>
  <% else %>
    <div class="jumbotron">
      <h1><%= @movie_title.upcase %> <small><i>(<%= link_to @movie_mpaa_rating, "http://www.mpaa.org/wp-content/uploads/2013/11/film_ratings1.jpg" %>)</i></small></h1>
      <p class="font"><i><%= truncate(@movie_synopsis, length: 225, separator: ".") %></i></p>
    </div>

    <div class="row">
      <div class="col-md-4 col-md-offset-1">
        <%= image_tag @movie_poster_original, class: "img-responsive"%>
      </div>

      <div class="col-md-7">
        <p><strong>Audience Score:</strong> <%= @movie_rating_a_score %> (<%= @movie_rating_audience %>)</p>
        <p><strong>Critics Score:</strong> <%= @movie_rating_c_score %> (<%= @movie_rating_critics %>)</p>
        <p><strong>Runtime:</strong> <%= @movie_runtime %> minutes</p>

        <% unless @movie_release_theater.blank? %>
          <p><strong>Theatical Release:</strong> <%= @movie_release_theater.strftime('%A %B %d, %Y') %></p>
        <% else %>
          <p><strong>Theatical Release:</strong> No Release Listed</p>
        <% end %>

        <% unless @movie_release_dvd.blank? %>
          <p><strong>DVD Release:</strong> <%= @movie_release_dvd.strftime('%A %B %d, %Y') %></p>
        <% else %>
          <p><strong>DVD Release:</strong> No Release Listed</p>
        <% end %>

        <h4 class="title"><i>Cast</i></h4>
        <% @movie['abridged_cast'].each do |actor| %>
          <p><span class="glyphicon glyphicon-user"></span> <%= actor['name'] %></p>
            <% if actor['characters'].blank? %>
                <p style="text-indent:10px"><span class="glyphicon glyphicon-film"></span> Screen character not listed.</p>
              <% else %>
                <p style="text-indent:10px"><span class="glyphicon glyphicon-film"></span> <%= actor['characters'][0] %></p>
            <% end %>
        <% end %>

      </div>
    </div>

    <div class="row">
      <div class="col-md-10 col-md-offset-1 syn">
        <strong class="title"><i>Synopsis:</i></strong> <%= @movie_synopsis %>
      </div>
    </div>

  <% end %>
<% end %>